# Generated by Django 4.1.3 on 2023-10-24 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Docket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('num_hours_worked', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.supplier')),
            ],
        ),
    ]
